[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200

lib_deps =
    h2zero/NimBLE-Arduino

build_flags =
    -D CONFIG_BT_NIMBLE_ENABLED
    -D CONFIG_BT_CTRL_ENABLED
    -D CONFIG_BT_BLE_ENABLED
    -D CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_INTERNAL

monitor_filters = esp32c3_usb_serial_jtag
