[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino

board_build.partitions = huge_app.csv

lib_deps =
    h2zero/NimBLE-Arduino
    Adafruit NeoPixel
    adafruit/Adafruit INA219@^1.1.0

build_flags =
    -D CONFIG_BT_NIMBLE_ENABLED
    -D CONFIG_BT_CTRL_ENABLED
    -D CONFIG_BT_BLE_ENABLED
    -D CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_INTERNAL
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

monitor_speed = 115200
monitor_filters = esp32c3_usb_serial_jtag
